# Address on which the server listens
listen_addr: 0.0.0.0:8900

# List of available models via the api. The name corresponds to a model
# that the service knows how to load, and the device is where the model
# is executed.
available_models:
- model: all-minilm-l12-v2
  device: cpu
  default: true
- model: text-embedding-ada-002
  device: remote

extractors:
- name: "bert-entity-extractor"
  path: "indexify_extractors.entity_extractor.EntityExtractor"
  driver: "python"
- name: "minilm-l6-v2-embeddings"
  path: "indexify_extractors.embedding_extractor.MiniLML6Extractor"
  driver: "python"

# OpenAI key. Either set it here or set via the OPENAI_API_KEY
# environment variable
openai:
  api_key: xxxxx

# Database URL for storing document and memory
db_url: postgres://postgres:postgres@localhost/indexify

coordinator_addr: 0.0.0.0:8950

executor_config:
  server_listen_addr: 0.0.0.0:8951

# Blob storage configuration for the service. It is used for storing
# raw data such as PDF, Images and Videos.
blob_storage:
  # The backend of the blob storage. Currently, only local file system
  # and S3 are supported.
  # Possible values - disk and s3
  backend: disk
  # Path to the directory where the blob storage will store the data.
  disk:
    path: /tmp/indexify-blob-storage

# Vector index configuration for the service. The index_store parameter
# specifies the type of index to use. Currently, only Qdrant is supported.
#
# The db_url parameter specifies the database url used for persistence of
# metadata related to the indexed vectors and documents.
#
# The qdrant_config parameter specifies the configuration for the Qdrant
# service.
index_config:
  index_store: Qdrant
  qdrant_config:
    addr: "http://127.0.0.1:6334"

# The pg_embedding_config parameter specifies the configuration for the Postgres pg_embedding extension
# index_config:
#   index_store: pg_embedding
#   pg_embedding_config:
#      addr: postgres://postgres:postgres@localhost/indexify
#      m: 3
#      efconstruction: 5
#      efsearch: 5

