# Network interface on which the server listens
listen_if: 0.0.0.0

# Port on which the server listens
#listen_port: 8900

# Port on which the coordinator listens
#coordinator_port: 8950

# Database URL for storing document and memory
db_url: postgres://postgres:postgres@postgres/indexify

# Address on which the coordinator is available for the API server
# to query for executors
coordinator_addr: 0.0.0.0:8950

raft_port: 8970

# Blob storage configuration for the service. It is used for storing
# raw data such as PDF, Images and Videos.
blob_storage:
  # The backend of the blob storage. Currently, only local file system
  # and S3 are supported.
  # Possible values - disk and s3
  backend: disk
  # Path to the directory where the blob storage will store the data.
  disk:
    path: /tmp/indexify-blob-storage

# Vector index configuration for the service. The index_store parameter
# specifies the type of index to use. Currently, only Qdrant is supported.
#
# The db_url parameter specifies the database url used for persistence of
# metadata related to the indexed vectors and documents.
#
# The qdrant_config parameter specifies the configuration for the Qdrant
# service.
index_config:
  # Possible values: Qdrant, PgEmbedding
  index_store: Qdrant
  qdrant_config:
    addr: "http://qdrant:6334"
# # The pg_vector_config parameter specifies the configuration for the Postgres pg_embedding extension
# - index_store: PgEmbedding
#   pg_vector_config:
#     addr: postgres://postgres:postgres@localhost/indexify
#     m: 16
#     efconstruction: 64
#     efsearch: 40

# If relative path is specified, it is relative to the project root directory
# You should replace the values with your own values
tls:
  api: false
  ca_file: .dev-tls/ca.crt # Path to the CA certificate; TODO: support custom CA in client
  cert_file: .dev-tls/server.crt # Path to the server certificate
  key_file: .dev-tls/server.key # Path to the server private key

node_id: 0
peers:
  - node_id: 0
    addr: localhost:8970

cache:
  # Possible values - redis, memory, none
  backend: memory

  redis:
    addr: redis://localhost:6379

  memory:
    max_size: 1000000
