{{- with .Values.coordinator }}
{{- if .enabled }}
{{- $statefulsetName := include "coordinator.fullname" . }}
{{- $replicaCount := .replicas | int }}
{{- range $i, $e := until $replicaCount }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $statefulsetName }}-config-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels" (dict "name" $statefulsetName "component" "config" "global" $) | nindent 4 }}
data:
  config.yaml: |-
    coordinator_addr: {{ $statefulsetName }}-0.{{ $statefulsetName }}.{{ $.Release.Namespace }}.svc.cluster.local:8950
    raft_port: 8970
    seed_node: {{ $statefulsetName }}-0.{{ $statefulsetName }}.{{ $.Release.Namespace }}.svc.cluster.local:8970
    node_id: {{ $i }}
    state_store:
      path: /data/state
    db_url: {{ $.Values.dbURL }}
    index_config:
      {{- $.Values.indexConfig| toYaml | nindent 6 }}
    metadata_storage:
      {{- $.Values.metadataStorage | toYaml | nindent 6 }}
    blob_storage:
      {{- $.Values.blobStore.config | toYaml | nindent 6 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
spec:
  clusterIP: None
  ports:
    - port: 8950
      name: coordinator
      targetPort: 8950
    - port: 8970
      name: seed
      targetPort: 8970
  selector:
    app: coordinator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "coordinator.fullname" . }}
  labels:
    {{- include "labels" (dict "name" "coordinator" "component" "coordinator" "global" $) | nindent 4 }}
spec:
  serviceName: {{ include "coordinator.fullname" . }}
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ include "coordinator.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "coordinator.fullname" . }}
    spec:
      containers:
        - name: indexify
          image: {{ .image }}
          command: ['indexify']
          args:
            - coordinator
            - --config-path
            - /etc/$(POD_NAME)/config.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            {{- range $i, $e := until $replicaCount }}
            - mountPath: /etc/coordinator-{{ $i }}
              name: config-{{ $i }}
              readOnly: true
            {{- end }}
            - mountPath: /data
              name: data
      volumes:
        {{- range $i, $e := until $replicaCount }}
        - name: config-{{ $i }}
          configMap:
            name: {{ $statefulsetName }}-config-{{ $i }}
        {{- end }}
        - name: data
          emptyDir: {}
{{- end }}
{{- end }}
