[package]
name = "data_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
derive_builder = "0.20.1"
anyhow = { workspace = true }
serde_json = { workspace = true }
indexify_utils = { workspace = true }
rand = {workspace=true}
uuid = {workspace=true}
sha2 = {workspace=true}
