apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
spec:
  selector:
    app: qdrant
  ports:
    - name: qdrant-http-port
      protocol: TCP
      port: 6333
      targetPort: 6333
    - name: qdrant-grpc-port
      protocol: TCP
      port: 6334
      targetPort: 6334
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:v1.1.3
          ports:
            - containerPort: 6333
            - containerPort: 6334
          volumeMounts:
            - name: qdrant-volume
              mountPath: /qdrant/storage
              subPath: qdrant
      volumes:
        - name: qdrant-volume
          persistentVolumeClaim:
            claimName: qdrant-pvc
