[package]
name = "dataplane"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde-saphyr = { workspace = true }
serde-inline-default = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
json-subscriber = { workspace = true }
bollard = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
libc = { workspace = true }
proto-api = { path = "../proto-api" }
