site_name: ''
site_url: https://docs.getindexify.ai/

repo_url: https://github.com/tensorlakeai/indexify
repo_name: tensorlakeai/indexify
edit_uri: edit/main/docs/docs
copyright: Copyright &copy; 2024 Tensorlake

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta

nav:
  - Home:
      - Indexify: index.md
      - Getting Started - Basic: 'getting_started.md'
      - Getting Started - Intermediate: 'getting_started_intermediate.md'
      - Key Concepts: 'concepts.md'
      - Architecture: 'architecture.md'
      - Comparisons: 'comparisons.md'
  - CLI and UI:
      - User Interface: 'ui.md'
      - Extractor CLI: 'extractor_cli.md'
      - Server CLI: 'server_cli.md'
  - Extractors:
      - Introduction: 'apis/extractors.md'
      - Develop Extractors: 'apis/develop_extractors.md'
      - Available Extractors:
          - Text: 'apis/extractors/text.md'
          - PDF: 'apis/extractors/pdf.md'
          - Image: 'apis/extractors/image.md'
          - Audio: 'apis/extractors/audio.md'
          - Video: 'apis/extractors/video.md'
          - Embedding: 'apis/extractors/embedding.md'
          - Web: 'apis/extractors/web.md'

  - APIs:
      - Install: 'apis/install_clients.md'
      - Content Ingestion: 'apis/content_ingestion.md'
      - Extraction Graphs: 'apis/extraction_graphs.md'
      - Retrieval: 'apis/retrieval.md'
  - Use Cases:
      - Basic RAG: 'usecases/rag.md'
      - Audio Extraction: 'usecases/audio_extraction.md'
      - PDF Extraction: 'usecases/pdf_extraction.md'
      - Image Retrieval: 'usecases/image_retrieval.md'
      - Video Understanding: 'usecases/video_rag.md'
  - LLM Frameworks:
      - Langchain:
          - Python: 'integrations/langchain/python_langchain.md'
          - TypeScript: 'integrations/langchain/typescript_langchain.md'
      - DSPy:
          - Python: 'integrations/dspy/python_dspy.md'
  - Deployment and Operation:
      - Kubernetes: 'operations/kubernetes.md'
      - Configuration: 'configuration.md'
      - Metrics: 'metrics.md'
      - Develop Indexify: 'develop.md'
      - Extractors on GPU: 'gpu-deployment.md'
  - Examples:
      - All Examples: 'examples/landing.md'

plugins:
  - mkdocs-jupyter

theme:
  name: material
  custom_dir: overrides
  logo: ./images/Indexify_Logo_Wordmark_Dark.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  features:
    - content.action.edit
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false
  analytics:
    provider: google
    property: G-KCZ6YYKGKR
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mrXrq3DmV8
      name: Indexify Discord Community
    - icon: fontawesome/solid/paper-plane
      link: mailto:<diptanuc@gmail.com>
      name: Email

extra_css:
  - stylesheets/extras.css
