name: Indexify Deb Build

# on: workflow_dispatch
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  debbuild:
    runs-on: ubuntu-latest
    name: Build Deb And Push r2 Repo
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install protoc
        run: sudo apt update && sudo apt install protobuf-compiler -y
      - name: Cargo check
        run: cargo check
      - name: Make build-release
        run: make build-release
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build and Package
        run: cargo deb
      - name: install reprepro
        run: sudo apt-get update && sudo apt-get install -y reprepro
      # - name: Run reprepro
      #   run: |
      #     cd .repo
      #     reprepro includedeb buster ../target/debian/*.deb
      #     reprepro includedeb focal ../target/debian/*.deb
      #     reprepro includedeb jammy ../target/debian/*.deb
      # - uses: ryand56/r2-upload-action@latest
      #   with:
      #     r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
      #     r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
      #     r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      #     r2-bucket: ${{ secrets.R2_BUCKET }}
      #     source-dir: .repo
      #     destination-dir: ./repo
